module UeberDenHof.View

open Fable.Helpers.React
open Fulma

let root =
  [ Content.content []
      [ Heading.h1 [ Heading.Is3 ]
          [ str "Über den Hof" ]
        Heading.h2 [ Heading.Is4 ]
          [ str "Tiere" ]
        Heading.h3 [ Heading.Is5 ]
          [ str "Lilly & Paula" ]
        p [ ]
          [ str "Unsere beiden Esel" ]
        Heading.h3 [ Heading.Is5 ]
          [ str "Laika & Luna" ]
        p [ ]
          [ str "Mama-Pony und ihr Fohlen" ]
        Heading.h3 [ Heading.Is5 ]
          [ str "Josephine & Rosi" ]
        p [ ]
          [ str "Unsere unzähmbaren Kühe" ]
        Heading.h3 [ Heading.Is5 ]
          [ str "Hahn & Hühner" ]
        p [ ]
          [ str "Ein Hahn und seine 13 Hühner" ]
        Heading.h3 [ Heading.Is5 ]
          [ str "Minki & Quetschi" ]
        p [ ]
          [ str "Hasenmama und -papa" ]
        Heading.h3 [ Heading.Is5 ]
          [ str "Maxi" ]
        p [ ]
          [ str "Unser Mäusefänger" ]
        Heading.h3 [ Heading.Is5 ]
          [ str "Puma" ]
        p [ ]
          [ str "Hofwächter ohne Wachfunktion" ] ] ]
